// This file is generated by scripts/generate-manifests.ts. Do not edit.
import type { ComponentManifest } from '@studiometa/js-toolkit';

export const manifest: ComponentManifest = {
  Motion: {
    token: 'Motion',
    packageName: '@studiometa/ui-motion',
    subpath: 'Motion',
    exportName: 'Motion',
    strategy: 'visible',
    group: 'motion',
    load: () => import('./Motion.js').then(({ Motion }) => Motion),
  },
  MotionScrollTimeline: {
    token: 'MotionScrollTimeline',
    packageName: '@studiometa/ui-motion',
    subpath: 'MotionScrollTimeline',
    exportName: 'MotionScrollTimeline',
    strategy: 'visible',
    group: 'motion',
    children: ['Motion'],
    load: () =>
      import('./MotionScrollTimeline.js').then(({ MotionScrollTimeline }) => MotionScrollTimeline),
  },
  MotionSequence: {
    token: 'MotionSequence',
    packageName: '@studiometa/ui-motion',
    subpath: 'MotionSequence',
    exportName: 'MotionSequence',
    strategy: 'visible',
    group: 'motion',
    children: ['Motion'],
    load: () => import('./MotionSequence.js').then(({ MotionSequence }) => MotionSequence),
  },
  MotionView: {
    token: 'MotionView',
    packageName: '@studiometa/ui-motion',
    subpath: 'MotionView',
    exportName: 'MotionView',
    strategy: 'visible',
    group: 'motion',
    load: () => import('./MotionView.js').then(({ MotionView }) => MotionView),
  },
};
