// This file is generated by scripts/generate-manifests.ts. Do not edit.
import type { ComponentManifest } from '@studiometa/js-toolkit';

export const manifest: ComponentManifest = {
  Motion: {
    token: 'Motion',
    packageName: '@studiometa/ui-motion',
    subpath: 'Motion',
    exportName: 'Motion',
    strategy: 'visible',
    group: 'motion',
    load: () => import('./Motion.js').then(({ Motion }) => Motion),
  },
};
