image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      nvm install 20
      nvm use 20
      npm i --no-audit --no-fund
      npm run docs:build
    command: |
      ddev start

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - mblode.twig-language-2

ports:
  - port: 8080
    onOpen: open-preview
