tasks:
  - init: |
      brew install ddev/ddev/ddev
      nvm install 20
      nvm use 20
      npm i --no-audit --no-fund
      npm run docs:build
      ddev start
    command: |
      apachectl start

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - mblode.twig-language-2

ports:
  - port: 8080
    onOpen: open-preview
