coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "packages/docs/**"
  - "packages/tests/**"
  - "**/node_modules/**"
  - "**/*.spec.ts"
  - "**/*.test.ts"
