// This file is generated by scripts/generate-manifests.ts. Do not edit.
import type { ComponentManifest } from '@studiometa/js-toolkit';

export const manifest: ComponentManifest = {
  MapboxCluster: {
    mountStrategy: 'visible',
    load: () => import('./MapboxCluster.js').then(({ MapboxCluster }) => MapboxCluster),
  },
  MapboxClusterItem: {
    mountStrategy: 'visible',
    load: () => import('./MapboxClusterItem.js').then(({ MapboxClusterItem }) => MapboxClusterItem),
  },
  MapboxFullscreenControl: {
    mountStrategy: 'visible',
    load: () =>
      import('./MapboxFullscreenControl.js').then(
        ({ MapboxFullscreenControl }) => MapboxFullscreenControl,
      ),
  },
  MapboxGeocoder: {
    mountStrategy: 'visible',
    load: () => import('./MapboxGeocoder.js').then(({ MapboxGeocoder }) => MapboxGeocoder),
  },
  MapboxGeolocateControl: {
    mountStrategy: 'visible',
    load: () =>
      import('./MapboxGeolocateControl.js').then(
        ({ MapboxGeolocateControl }) => MapboxGeolocateControl,
      ),
  },
  MapboxImage: {
    mountStrategy: 'visible',
    load: () => import('./MapboxImage.js').then(({ MapboxImage }) => MapboxImage),
  },
  MapboxImages: {
    mountStrategy: 'visible',
    load: () => import('./MapboxImages.js').then(({ MapboxImages }) => MapboxImages),
  },
  MapboxLayer: {
    mountStrategy: 'visible',
    load: () => import('./MapboxLayer.js').then(({ MapboxLayer }) => MapboxLayer),
  },
  MapboxMap: {
    mountStrategy: 'visible',
    load: () => import('./MapboxMap.js').then(({ MapboxMap }) => MapboxMap),
  },
  MapboxMarker: {
    mountStrategy: 'visible',
    load: () => import('./MapboxMarker.js').then(({ MapboxMarker }) => MapboxMarker),
  },
  MapboxNavigationControl: {
    mountStrategy: 'visible',
    load: () =>
      import('./MapboxNavigationControl.js').then(
        ({ MapboxNavigationControl }) => MapboxNavigationControl,
      ),
  },
  MapboxPopup: {
    mountStrategy: 'visible',
    load: () => import('./MapboxPopup.js').then(({ MapboxPopup }) => MapboxPopup),
  },
  MapboxSource: {
    mountStrategy: 'visible',
    load: () => import('./MapboxSource.js').then(({ MapboxSource }) => MapboxSource),
  },
  StoreLocator: {
    mountStrategy: 'visible',
    load: () => import('./StoreLocator.js').then(({ StoreLocator }) => StoreLocator),
  },
};
