twig:
    default_path: '%kernel.project_dir%/../ui/'
    paths:
        '%kernel.project_dir%/templates': private
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"

when@test:
    twig:
        strict_variables: true
