import type {
  ComponentCatalog,
  CuratedComponentMetadata,
} from '../../../scripts/manifest-types.js';

const components: readonly CuratedComponentMetadata[] = [
  { token: 'Action', group: 'action' },
  { token: 'Target', group: 'action' },
  {
    token: 'AnchorNav',
    group: 'anchor-nav',
    children: ['AnchorNavLink', 'AnchorNavTarget'],
  },
  { token: 'AnchorNavLink', group: 'anchor-nav' },
  { token: 'AnchorNavTarget', group: 'anchor-nav' },
  {
    token: 'Carousel',
    group: 'carousel',
    // `CarouselPlay` is deliberately absent: this list mirrors
    // `Carousel.config.components`, and the rotation control is registered by
    // the consumer, or by the autoload manifest, rather than by its parent.
    children: ['CarouselBtn', 'CarouselDrag', 'CarouselItem', 'CarouselWrapper'],
  },
  { token: 'CarouselBtn', group: 'carousel' },
  { token: 'CarouselDrag', group: 'carousel' },
  { token: 'CarouselItem', group: 'carousel' },
  { token: 'CarouselPlay', group: 'carousel' },
  { token: 'CarouselWrapper', group: 'carousel' },
  { token: 'CircularMarquee', group: 'circular-marquee' },
  { token: 'ClickOutside', group: 'click-outside' },
  { token: 'Cursor', group: 'cursor' },
  { token: 'DataBind', group: 'data' },
  { token: 'DataComputed', group: 'data' },
  { token: 'DataEffect', group: 'data' },
  { token: 'DataModel', group: 'data' },
  { token: 'DataScope', group: 'data' },
  { token: 'Defer', group: 'defer' },
  { token: 'Dialog', group: 'dialog', children: ['Transition', 'ViewTransition'] },
  { token: 'Disclosure', group: 'disclosure', children: ['Transition', 'ViewTransition'] },
  { token: 'DisclosureGroup', group: 'disclosure', children: ['Disclosure'] },
  { token: 'Draggable', group: 'draggable' },
  { token: 'Fetch', group: 'fetch' },
  { token: 'FetchShopifyPartial', group: 'fetch', integrations: ['shopify'] },
  { token: 'FetchShopifySection', group: 'fetch', integrations: ['shopify'] },
  { token: 'Figure', group: 'figure' },
  { token: 'FigureShopify', group: 'figure', integrations: ['shopify'] },
  { token: 'FigureTwicpics', group: 'figure', integrations: ['twicpics'] },
  { token: 'FigureVideo', group: 'figure-video' },
  { token: 'FigureVideoTwicpics', group: 'figure-video', integrations: ['twicpics'] },
  { token: 'Hoverable', group: 'hoverable' },
  { token: 'Indexable', group: 'indexable' },
  { token: 'InView', group: 'in-view' },
  { token: 'InViewOnce', group: 'in-view' },
  { token: 'LargeText', group: 'large-text' },
  { token: 'Menu', group: 'menu', children: ['MenuBtn', 'MenuList'] },
  { token: 'MenuBtn', group: 'menu' },
  { token: 'MenuList', group: 'menu', children: ['MenuList'] },
  { token: 'PrefetchOnInteraction', group: 'prefetch' },
  { token: 'PrefetchWhenVisible', group: 'prefetch' },
  { token: 'ScrollReveal', group: 'scroll-reveal' },
  { token: 'ScrollTo', group: 'scroll-to' },
  { token: 'Sentinel', group: 'sentinel' },
  { token: 'Slider', group: 'slider', children: ['SliderItem', 'SliderDrag'] },
  { token: 'SliderBtn', group: 'slider' },
  { token: 'SliderCount', group: 'slider' },
  { token: 'SliderDots', group: 'slider' },
  { token: 'SliderDrag', group: 'slider' },
  { token: 'SliderItem', group: 'slider' },
  { token: 'SliderProgress', group: 'slider' },
  { token: 'Sticky', group: 'sticky', children: ['Sentinel'] },
  { token: 'Tabs', group: 'tabs' },
  { token: 'Timer', group: 'timer' },
  { token: 'TimerProgress', group: 'timer' },
  { token: 'Toast', group: 'toaster' },
  { token: 'Toaster', group: 'toaster', children: ['Toast'] },
  { token: 'Track', group: 'track' },
  { token: 'TrackContext', group: 'track' },
  { token: 'TrackShopify', group: 'track', integrations: ['shopify'] },
  { token: 'Transition', group: 'transition' },
  { token: 'ViewTransition', group: 'transition' },
];

/** The autoload catalog for every declarative `@studiometa/ui` component. */
export const catalog: ComponentCatalog = {
  packageName: '@studiometa/ui',
  strategy: 'eager',
  components,
  abstractExports: [
    'AbstractCarouselChild',
    'AbstractCarouselComponent',
    'AbstractFigure',
    'AbstractFigureDynamic',
    'AbstractPrefetch',
    'AbstractTrack',
    'ActionEvent',
    'DataRegistry',
    'TrackEvent',
  ],
};
