// This file is generated by scripts/generate-manifests.ts. Do not edit.
import type { ComponentManifest } from '@studiometa/js-toolkit';

export const manifest: ComponentManifest = {
  Action: {
    mountStrategy: 'eager',
    load: () => import('./Action/Action.js').then(({ Action }) => Action),
  },
  AnchorNav: {
    mountStrategy: 'eager',
    load: () => import('./AnchorNav/AnchorNav.js').then(({ AnchorNav }) => AnchorNav),
  },
  AnchorNavLink: {
    mountStrategy: 'eager',
    load: () => import('./AnchorNav/AnchorNavLink.js').then(({ AnchorNavLink }) => AnchorNavLink),
  },
  AnchorNavTarget: {
    mountStrategy: 'eager',
    load: () =>
      import('./AnchorNav/AnchorNavTarget.js').then(({ AnchorNavTarget }) => AnchorNavTarget),
  },
  Carousel: {
    mountStrategy: 'eager',
    load: () => import('./Carousel/Carousel.js').then(({ Carousel }) => Carousel),
  },
  CarouselBtn: {
    mountStrategy: 'eager',
    load: () => import('./Carousel/CarouselBtn.js').then(({ CarouselBtn }) => CarouselBtn),
  },
  CarouselCount: {
    mountStrategy: 'eager',
    load: () => import('./Carousel/CarouselCount.js').then(({ CarouselCount }) => CarouselCount),
  },
  CarouselDots: {
    mountStrategy: 'eager',
    load: () => import('./Carousel/CarouselDots.js').then(({ CarouselDots }) => CarouselDots),
  },
  CarouselDrag: {
    mountStrategy: 'eager',
    load: () => import('./Carousel/CarouselDrag.js').then(({ CarouselDrag }) => CarouselDrag),
  },
  CarouselItem: {
    mountStrategy: 'eager',
    load: () => import('./Carousel/CarouselItem.js').then(({ CarouselItem }) => CarouselItem),
  },
  CarouselPlay: {
    mountStrategy: 'eager',
    load: () => import('./Carousel/CarouselPlay.js').then(({ CarouselPlay }) => CarouselPlay),
  },
  CarouselProgress: {
    mountStrategy: 'eager',
    load: () =>
      import('./Carousel/CarouselProgress.js').then(({ CarouselProgress }) => CarouselProgress),
  },
  CarouselThumbnails: {
    mountStrategy: 'eager',
    load: () =>
      import('./Carousel/CarouselThumbnails.js').then(
        ({ CarouselThumbnails }) => CarouselThumbnails,
      ),
  },
  CarouselWrapper: {
    mountStrategy: 'eager',
    load: () =>
      import('./Carousel/CarouselWrapper.js').then(({ CarouselWrapper }) => CarouselWrapper),
  },
  CircularMarquee: {
    mountStrategy: 'eager',
    load: () =>
      import('./CircularMarquee/CircularMarquee.js').then(({ CircularMarquee }) => CircularMarquee),
  },
  ClickOutside: {
    mountStrategy: 'eager',
    load: () => import('./ClickOutside/ClickOutside.js').then(({ ClickOutside }) => ClickOutside),
  },
  Cursor: {
    mountStrategy: 'eager',
    load: () => import('./Cursor/Cursor.js').then(({ Cursor }) => Cursor),
  },
  DataBind: {
    mountStrategy: 'eager',
    load: () => import('./Data/DataBind.js').then(({ DataBind }) => DataBind),
  },
  DataComputed: {
    mountStrategy: 'eager',
    load: () => import('./Data/DataComputed.js').then(({ DataComputed }) => DataComputed),
  },
  DataEffect: {
    mountStrategy: 'eager',
    load: () => import('./Data/DataEffect.js').then(({ DataEffect }) => DataEffect),
  },
  DataModel: {
    mountStrategy: 'eager',
    load: () => import('./Data/DataModel.js').then(({ DataModel }) => DataModel),
  },
  DataScope: {
    mountStrategy: 'eager',
    load: () => import('./Data/DataScope.js').then(({ DataScope }) => DataScope),
  },
  Defer: {
    mountStrategy: 'eager',
    load: () => import('./Defer/Defer.js').then(({ Defer }) => Defer),
  },
  Dialog: {
    mountStrategy: 'eager',
    load: () => import('./Dialog/Dialog.js').then(({ Dialog }) => Dialog),
  },
  Disclosure: {
    mountStrategy: 'eager',
    load: () => import('./Disclosure/Disclosure.js').then(({ Disclosure }) => Disclosure),
  },
  DisclosureGroup: {
    mountStrategy: 'eager',
    load: () =>
      import('./Disclosure/DisclosureGroup.js').then(({ DisclosureGroup }) => DisclosureGroup),
  },
  Draggable: {
    mountStrategy: 'eager',
    load: () => import('./Draggable/Draggable.js').then(({ Draggable }) => Draggable),
  },
  Fetch: {
    mountStrategy: 'eager',
    load: () => import('./Fetch/Fetch.js').then(({ Fetch }) => Fetch),
  },
  FetchShopifyPartial: {
    mountStrategy: 'eager',
    load: () =>
      import('./Fetch/FetchShopifyPartial.js').then(
        ({ FetchShopifyPartial }) => FetchShopifyPartial,
      ),
  },
  FetchShopifySection: {
    mountStrategy: 'eager',
    load: () =>
      import('./Fetch/FetchShopifySection.js').then(
        ({ FetchShopifySection }) => FetchShopifySection,
      ),
  },
  Figure: {
    mountStrategy: 'eager',
    load: () => import('./Figure/Figure.js').then(({ Figure }) => Figure),
  },
  FigureShopify: {
    mountStrategy: 'eager',
    load: () => import('./Figure/FigureShopify.js').then(({ FigureShopify }) => FigureShopify),
  },
  FigureTwicpics: {
    mountStrategy: 'eager',
    load: () => import('./Figure/FigureTwicpics.js').then(({ FigureTwicpics }) => FigureTwicpics),
  },
  FigureVideo: {
    mountStrategy: 'eager',
    load: () => import('./FigureVideo/FigureVideo.js').then(({ FigureVideo }) => FigureVideo),
  },
  FigureVideoTwicpics: {
    mountStrategy: 'eager',
    load: () =>
      import('./FigureVideo/FigureVideoTwicpics.js').then(
        ({ FigureVideoTwicpics }) => FigureVideoTwicpics,
      ),
  },
  Hoverable: {
    mountStrategy: 'eager',
    load: () => import('./Hoverable/Hoverable.js').then(({ Hoverable }) => Hoverable),
  },
  Indexable: {
    mountStrategy: 'eager',
    load: () => import('./Indexable/Indexable.js').then(({ Indexable }) => Indexable),
  },
  InView: {
    mountStrategy: 'eager',
    load: () => import('./InView/InView.js').then(({ InView }) => InView),
  },
  InViewOnce: {
    mountStrategy: 'eager',
    load: () => import('./InView/InViewOnce.js').then(({ InViewOnce }) => InViewOnce),
  },
  LargeText: {
    mountStrategy: 'eager',
    load: () => import('./LargeText/LargeText.js').then(({ LargeText }) => LargeText),
  },
  Menu: {
    mountStrategy: 'eager',
    load: () => import('./Menu/Menu.js').then(({ Menu }) => Menu),
  },
  MenuBtn: {
    mountStrategy: 'eager',
    load: () => import('./Menu/MenuBtn.js').then(({ MenuBtn }) => MenuBtn),
  },
  MenuList: {
    mountStrategy: 'eager',
    load: () => import('./Menu/MenuList.js').then(({ MenuList }) => MenuList),
  },
  PrefetchOnInteraction: {
    mountStrategy: 'eager',
    load: () =>
      import('./Prefetch/PrefetchOnInteraction.js').then(
        ({ PrefetchOnInteraction }) => PrefetchOnInteraction,
      ),
  },
  PrefetchWhenVisible: {
    mountStrategy: 'eager',
    load: () =>
      import('./Prefetch/PrefetchWhenVisible.js').then(
        ({ PrefetchWhenVisible }) => PrefetchWhenVisible,
      ),
  },
  ScrollReveal: {
    mountStrategy: 'eager',
    load: () => import('./ScrollReveal/ScrollReveal.js').then(({ ScrollReveal }) => ScrollReveal),
  },
  ScrollTo: {
    mountStrategy: 'eager',
    load: () => import('./ScrollTo/ScrollTo.js').then(({ ScrollTo }) => ScrollTo),
  },
  Sentinel: {
    mountStrategy: 'eager',
    load: () => import('./Sentinel/Sentinel.js').then(({ Sentinel }) => Sentinel),
  },
  Sticky: {
    mountStrategy: 'eager',
    load: () => import('./Sticky/Sticky.js').then(({ Sticky }) => Sticky),
  },
  Tabs: {
    mountStrategy: 'eager',
    load: () => import('./Tabs/Tabs.js').then(({ Tabs }) => Tabs),
  },
  Target: {
    mountStrategy: 'eager',
    load: () => import('./Action/Target.js').then(({ Target }) => Target),
  },
  Timer: {
    mountStrategy: 'eager',
    load: () => import('./Timer/Timer.js').then(({ Timer }) => Timer),
  },
  TimerProgress: {
    mountStrategy: 'eager',
    load: () => import('./Timer/TimerProgress.js').then(({ TimerProgress }) => TimerProgress),
  },
  Toast: {
    mountStrategy: 'eager',
    load: () => import('./Toaster/Toast.js').then(({ Toast }) => Toast),
  },
  Toaster: {
    mountStrategy: 'eager',
    load: () => import('./Toaster/Toaster.js').then(({ Toaster }) => Toaster),
  },
  Track: {
    mountStrategy: 'eager',
    load: () => import('./Track/Track.js').then(({ Track }) => Track),
  },
  TrackContext: {
    mountStrategy: 'eager',
    load: () => import('./Track/TrackContext.js').then(({ TrackContext }) => TrackContext),
  },
  TrackShopify: {
    mountStrategy: 'eager',
    load: () => import('./Track/TrackShopify.js').then(({ TrackShopify }) => TrackShopify),
  },
  Transition: {
    mountStrategy: 'eager',
    load: () => import('./Transition/Transition.js').then(({ Transition }) => Transition),
  },
  ViewTransition: {
    mountStrategy: 'eager',
    load: () =>
      import('./ViewTransition/ViewTransition.js').then(({ ViewTransition }) => ViewTransition),
  },
};
