/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IOcticonLinkExternal16: typeof import('~icons/octicon/link-external16')['default']
    IOcticonPlusCircle16: typeof import('~icons/octicon/plus-circle16')['default']
    IOcticonSync16: typeof import('~icons/octicon/sync16')['default']
    IOcticonXCircle16: typeof import('~icons/octicon/x-circle16')['default']
  }
}
