// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IOcticonLinkExternal16: typeof import('~icons/octicon/link-external16')['default']
    IOcticonSync16: typeof import('~icons/octicon/sync16')['default']
  }
}

export { }
