// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IOcticonChevronDown16: typeof import('~icons/octicon/chevron-down16')['default']
    IOcticonCode16: typeof import('~icons/octicon/code16')['default']
    IOcticonCodeSquare16: typeof import('~icons/octicon/code-square16')['default']
    IOcticonLinkExternal16: typeof import('~icons/octicon/link-external16')['default']
    IOcticonMinusCircle16: typeof import('~icons/octicon/minus-circle16')['default']
    IOcticonPlusCircle16: typeof import('~icons/octicon/plus-circle16')['default']
    IOcticonSkip16: typeof import('~icons/octicon/skip16')['default']
    IOcticonSync16: typeof import('~icons/octicon/sync16')['default']
    IOcticonXCircle16: typeof import('~icons/octicon/x-circle16')['default']
  }
}

export { }
