import type {
  ReferenceCatalogEntry,
  ReferenceCatalogFilters,
  ReferenceCatalogGroup,
  ReferenceKind,
  ReferenceStatus,
  ReferenceSymbol,
  ReferenceSymbolKind,
} from './types';
import { publicContractSymbols } from './public-contracts.ts';

const uiPackage = 'npm:@studiometa/ui' as const;
const twigPackage = 'composer:studiometa/ui' as const;
const mapboxPackage = 'npm:@studiometa/ui-mapbox' as const;
const motionPackage = 'npm:@studiometa/ui-motion' as const;

export const kindLabels: Record<ReferenceKind, string> = {
  component: 'Components',
  primitive: 'Primitives',
  decorator: 'Decorators',
  helper: 'Helpers',
};

export const componentTaskLabels = {
  action: 'Trigger an action',
  animation: 'Animate content',
  data: 'Bind reactive data',
  disclosure: 'Show and hide content',
  dragging: 'Handle dragging',
  layout: 'Build a layout',
  loading: 'Load content',
  maps: 'Build a map',
  media: 'Display media',
  navigation: 'Navigate content',
  overlay: 'Open an overlay',
  timing: 'Coordinate timing',
  tracking: 'Track interactions',
} as const;

function uiSymbol(
  name: string,
  href: string,
  importName = name,
  kind: ReferenceSymbolKind = 'component',
  status?: ReferenceStatus,
): ReferenceSymbol {
  return {
    name,
    kind,
    package: uiPackage,
    importPath: `@studiometa/ui/${importName}`,
    href,
    ...(status ? { status } : {}),
  };
}

function twigSymbol(
  name: string,
  href: string,
  importPath: string,
  status?: ReferenceStatus,
): ReferenceSymbol {
  return {
    name,
    kind: 'template',
    package: twigPackage,
    importPath,
    href,
    ...(status ? { status } : {}),
  };
}

function mapboxSymbol(
  name: string,
  href: string,
  kind: ReferenceSymbolKind = 'component',
): ReferenceSymbol {
  return {
    name,
    kind,
    package: mapboxPackage,
    importPath: '@studiometa/ui-mapbox',
    href,
  };
}

function motionSymbol(
  name: string,
  href: string,
  kind: ReferenceSymbolKind = 'component',
): ReferenceSymbol {
  return {
    name,
    kind,
    package: motionPackage,
    importPath: '@studiometa/ui-motion',
    href,
  };
}

const frameTypes = [
  'FrameRequestInit',
  'FrameTriggerEvent',
  'FrameFetchEvent',
  'FrameFetchBeforeEvent',
  'FrameFetchAfterEvent',
  'FrameErrorEvent',
  'FrameContentEvent',
  'FrameContentAfterEvent',
].map((name) => uiSymbol(name, '/reference/items/Frame/js-api/', 'types', 'type'));

export const referenceCatalog = [
  {
    id: 'accordion',
    title: 'Accordion',
    summary: 'Build an accessible collection of independently expandable sections.',
    kind: 'component',
    path: '/reference/items/Accordion/',
    family: 'disclosure',
    primaryTask: 'disclosure',
    tags: ['accordion', 'collapse', 'disclosure', 'accessibility'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'deprecated',
    symbols: [
      uiSymbol('Accordion', '/reference/items/Accordion/', 'Accordion', 'component', 'deprecated'),
      uiSymbol(
        'AccordionItem',
        '/reference/items/Accordion/anatomy',
        'AccordionItem',
        'component',
        'deprecated',
      ),
      twigSymbol(
        'Accordion.twig',
        '/reference/items/Accordion/twig-api',
        '@ui/Accordion/Accordion.twig',
        'deprecated',
      ),
    ],
    capabilities: ['multiple items'],
    related: ['disclosure', 'tabs'],
  },
  {
    id: 'action',
    title: 'Action',
    summary: 'Map declarative DOM events to methods on components and targets.',
    kind: 'component',
    path: '/reference/items/Action/',
    family: 'actions',
    primaryTask: 'action',
    tags: ['events', 'actions', 'target', 'delegation'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Action', '/reference/items/Action/js-api'),
      uiSymbol('Target', '/reference/items/Action/js-api'),
    ],
    capabilities: ['debounce', 'event delegation', 'multiple events'],
    related: ['data-scope', 'dialog'],
  },
  {
    id: 'anchor-nav',
    title: 'AnchorNav',
    summary: 'Keep anchor navigation state synchronized with sections in view.',
    kind: 'component',
    path: '/reference/items/AnchorNav/',
    family: 'navigation',
    primaryTask: 'navigation',
    tags: ['anchor', 'navigation', 'scrollspy', 'sections'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('AnchorNav', '/reference/items/AnchorNav/js-api'),
      uiSymbol('AnchorNavLink', '/reference/items/AnchorNav/js-api'),
      uiSymbol('AnchorNavTarget', '/reference/items/AnchorNav/js-api'),
    ],
    related: ['anchor-scroll-to', 'in-view'],
  },
  {
    id: 'anchor-scroll-to',
    title: 'AnchorScrollTo',
    summary: 'Scroll smoothly to an anchor while preserving native link behavior.',
    kind: 'component',
    path: '/reference/items/AnchorScrollTo/',
    family: 'navigation',
    primaryTask: 'navigation',
    tags: ['anchor', 'scroll', 'smooth-scroll', 'navigation'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('AnchorScrollTo', '/reference/items/AnchorScrollTo/js-api')],
    aliases: ['AnchorScrollto'],
    related: ['anchor-nav'],
  },
  {
    id: 'button',
    title: 'Button',
    summary: 'Render composable button and link templates with icons and style variants.',
    kind: 'component',
    path: '/reference/items/Button/',
    family: 'actions',
    primaryTask: 'action',
    tags: ['button', 'link', 'icon', 'twig'],
    surfaces: ['twig'],
    packages: [twigPackage],
    status: 'stable',
    symbols: [
      twigSymbol('Button.twig', '/reference/items/Button/twig-api', '@ui/Button/Button.twig'),
      twigSymbol(
        'StyledButton.twig',
        '/reference/items/Button/twig-api',
        '@ui/Button/StyledButton.twig',
      ),
      twigSymbol(
        'StyledButtonRounded.twig',
        '/reference/items/Button/twig-api',
        '@ui/Button/StyledButtonRounded.twig',
      ),
    ],
    capabilities: ['icons', 'link rendering', 'style variants'],
  },
  {
    id: 'carousel',
    title: 'Carousel',
    summary: 'Compose scrollable carousels from wrappers, items, controls, and drag behavior.',
    kind: 'component',
    path: '/reference/items/Carousel/',
    family: 'carousel',
    primaryTask: 'navigation',
    tags: ['carousel', 'slider', 'drag', 'scroll'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Carousel', '/reference/items/Carousel/js-api'),
      uiSymbol('CarouselBtn', '/reference/items/Carousel/js-api'),
      uiSymbol('CarouselDrag', '/reference/items/Carousel/js-api'),
      uiSymbol('CarouselItem', '/reference/items/Carousel/js-api'),
      uiSymbol('CarouselWrapper', '/reference/items/Carousel/js-api'),
      uiSymbol(
        'AbstractCarouselComponent',
        '/reference/items/Carousel/js-api',
        'AbstractCarouselComponent',
        'primitive',
      ),
      uiSymbol(
        'AbstractCarouselChild',
        '/reference/items/Carousel/js-api',
        'AbstractCarouselChild',
        'primitive',
      ),
    ],
    capabilities: ['dragging', 'horizontal and vertical axes', 'nested controls'],
    related: ['draggable', 'slider'],
  },
  {
    id: 'circular-marquee',
    title: 'CircularMarquee',
    summary: 'Lay out and animate repeating text around a circular path.',
    kind: 'component',
    path: '/reference/items/CircularMarquee/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['marquee', 'circular', 'text', 'animation'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('CircularMarquee', '/reference/items/CircularMarquee/'),
      twigSymbol(
        'CircularMarquee.twig',
        '/reference/items/CircularMarquee/twig-api',
        '@ui/CircularMarquee/CircularMarquee.twig',
      ),
    ],
  },
  {
    id: 'click-outside',
    title: 'ClickOutside',
    summary: 'Detect pointer interaction outside an element without prescribing UI.',
    kind: 'primitive',
    path: '/reference/items/ClickOutside/',
    family: 'interaction',
    primaryTask: 'action',
    tags: ['click', 'outside', 'dismiss', 'events'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('ClickOutside', '/reference/items/ClickOutside/js-api', 'ClickOutside', 'primitive'),
    ],
    related: ['dialog', 'menu'],
  },
  {
    id: 'cursor',
    title: 'Cursor',
    summary: 'Render a custom cursor that reacts to pointer movement and hover targets.',
    kind: 'component',
    path: '/reference/items/Cursor/',
    family: 'interaction',
    primaryTask: 'animation',
    tags: ['cursor', 'pointer', 'hover', 'animation'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Cursor', '/reference/items/Cursor/js-api'),
      twigSymbol('Cursor.twig', '/reference/items/Cursor/twig-api', '@ui/Cursor/Cursor.twig'),
    ],
    related: ['hoverable'],
  },
  {
    id: 'data-bind',
    title: 'DataBind',
    summary: 'Reflect reactive values into attributes, properties, classes, or text.',
    kind: 'component',
    path: '/reference/items/DataBind/',
    family: 'data',
    primaryTask: 'data',
    tags: ['data', 'binding', 'reactivity', 'signals'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('DataBind', '/reference/items/DataBind/js-api')],
    related: ['data-computed', 'data-effect', 'data-model', 'data-scope'],
  },
  {
    id: 'data-computed',
    title: 'DataComputed',
    summary: 'Derive reactive values from data exposed by a scope.',
    kind: 'component',
    path: '/reference/items/DataComputed/',
    family: 'data',
    primaryTask: 'data',
    tags: ['data', 'computed', 'reactivity', 'signals'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('DataComputed', '/reference/items/DataComputed/js-api')],
    related: ['data-bind', 'data-effect', 'data-scope'],
  },
  {
    id: 'data-effect',
    title: 'DataEffect',
    summary: 'Run declarative side effects whenever scoped reactive values change.',
    kind: 'component',
    path: '/reference/items/DataEffect/',
    family: 'data',
    primaryTask: 'data',
    tags: ['data', 'effect', 'reactivity', 'signals'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('DataEffect', '/reference/items/DataEffect/js-api')],
    related: ['data-bind', 'data-computed', 'data-scope'],
  },
  {
    id: 'data-model',
    title: 'DataModel',
    summary: 'Synchronize form controls with reactive values using declarative models.',
    kind: 'component',
    path: '/reference/items/DataModel/',
    family: 'data',
    primaryTask: 'data',
    tags: ['data', 'model', 'forms', 'reactivity'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('DataModel', '/reference/items/DataModel/js-api')],
    related: ['data-bind', 'data-scope'],
  },
  {
    id: 'data-scope',
    title: 'DataScope',
    summary: 'Provide an isolated reactive data scope to descendant data components.',
    kind: 'component',
    path: '/reference/items/DataScope/',
    family: 'data',
    primaryTask: 'data',
    tags: ['data', 'scope', 'reactivity', 'state'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('DataScope', '/reference/items/DataScope/js-api')],
    capabilities: ['nested scopes', 'shared state'],
    related: ['data-bind', 'data-computed', 'data-effect', 'data-model'],
  },
  {
    id: 'dialog',
    title: 'Dialog',
    summary: 'Coordinate native dialogs, delegated triggers, and optional transitions.',
    kind: 'component',
    path: '/reference/items/Dialog/',
    family: 'overlay',
    primaryTask: 'overlay',
    tags: ['dialog', 'modal', 'drawer', 'overlay'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('Dialog', '/reference/items/Dialog/js-api')],
    capabilities: ['native dialog', 'delegated triggers', 'transitions'],
    related: ['action', 'modal', 'panel', 'transition'],
  },
  {
    id: 'disclosure',
    title: 'Disclosure',
    summary: 'Build accessible standalone disclosures and dynamically registered accordion groups.',
    kind: 'component',
    path: '/reference/items/Disclosure/',
    family: 'disclosure',
    primaryTask: 'disclosure',
    tags: ['accordion', 'collapse', 'disclosure', 'accessibility'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Disclosure', '/reference/items/Disclosure/js-api'),
      uiSymbol('DisclosureGroup', '/reference/items/Disclosure/js-api'),
      twigSymbol(
        'Disclosure.twig',
        '/reference/items/Disclosure/twig-api',
        '@ui/Disclosure/Disclosure.twig',
      ),
    ],
    capabilities: ['dynamic children', 'nested groups', 'single or multiple panels', 'transitions'],
    related: ['accordion', 'data-scope', 'transition', 'view-transition'],
  },
  {
    id: 'draggable',
    title: 'Draggable',
    summary: 'Add bounded pointer dragging with axis and movement controls.',
    kind: 'component',
    path: '/reference/items/Draggable/',
    family: 'interaction',
    primaryTask: 'dragging',
    tags: ['drag', 'pointer', 'bounds', 'gesture'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('Draggable', '/reference/items/Draggable/js-api')],
    capabilities: ['bounds', 'dynamic parent', 'strict bounds'],
    related: ['carousel', 'slider'],
  },
  {
    id: 'fetch',
    title: 'Fetch',
    summary: 'Fetch and replace server-rendered content with loaders and transitions.',
    kind: 'component',
    path: '/reference/items/Fetch/',
    family: 'loading',
    primaryTask: 'loading',
    tags: ['fetch', 'ajax', 'forms', 'partial navigation'],
    surfaces: ['js', 'liquid'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('Fetch', '/reference/items/Fetch/js-api')],
    capabilities: ['abort', 'forms', 'loaders', 'transitions'],
    related: ['fetch-shopify-partial', 'fetch-shopify-section', 'frame'],
  },
  {
    id: 'fetch-shopify-partial',
    title: 'FetchShopifyPartial',
    summary: 'Refresh Shopify partials while preserving client-side interaction state.',
    kind: 'component',
    path: '/reference/items/FetchShopifyPartial/',
    family: 'loading',
    primaryTask: 'loading',
    tags: ['fetch', 'shopify', 'partial rendering', 'liquid'],
    surfaces: ['js', 'liquid'],
    packages: [uiPackage],
    status: 'preview',
    symbols: [
      uiSymbol(
        'FetchShopifyPartial',
        '/reference/items/FetchShopifyPartial/js-api',
        'FetchShopifyPartial',
        'component',
        'preview',
      ),
    ],
    capabilities: ['focus preservation', 'form state preservation', 'view transitions'],
    related: ['fetch', 'fetch-shopify-section'],
  },
  {
    id: 'fetch-shopify-section',
    title: 'FetchShopifySection',
    summary: 'Update Shopify sections through the stable Section Rendering API.',
    kind: 'component',
    path: '/reference/items/FetchShopifySection/',
    family: 'loading',
    primaryTask: 'loading',
    tags: ['fetch', 'shopify', 'sections', 'liquid'],
    surfaces: ['js', 'liquid'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('FetchShopifySection', '/reference/items/FetchShopifySection/js-api')],
    related: ['fetch', 'fetch-shopify-partial'],
  },
  {
    id: 'figure',
    title: 'Figure',
    summary: 'Render responsive images with lazy loading, placeholders, and captions.',
    kind: 'component',
    path: '/reference/items/Figure/',
    family: 'media',
    primaryTask: 'media',
    tags: ['image', 'figure', 'responsive', 'lazy loading'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Figure', '/reference/items/Figure/js-api'),
      twigSymbol('Figure.twig', '/reference/items/Figure/twig-api', '@ui/Figure/Figure.twig'),
    ],
    capabilities: ['lazy loading', 'placeholders', 'responsive images'],
    related: ['figure-shopify', 'figure-twicpics', 'figure-video', 'image-grid'],
  },
  {
    id: 'figure-shopify',
    title: 'FigureShopify',
    summary: 'Load responsive images from Shopify CDN URLs in Liquid storefronts.',
    kind: 'component',
    path: '/reference/items/FigureShopify/',
    family: 'media',
    primaryTask: 'media',
    tags: ['image', 'shopify', 'cdn', 'liquid'],
    surfaces: ['js', 'liquid'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('FigureShopify', '/reference/items/FigureShopify/js-api')],
    related: ['figure'],
  },
  {
    id: 'figure-twicpics',
    title: 'FigureTwicpics',
    summary: 'Render and optimize responsive images through the TwicPics CDN.',
    kind: 'component',
    path: '/reference/items/FigureTwicpics/',
    family: 'media',
    primaryTask: 'media',
    tags: ['image', 'twicpics', 'cdn', 'responsive'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('FigureTwicpics', '/reference/items/FigureTwicpics/js-api'),
      twigSymbol(
        'FigureTwicpics.twig',
        '/reference/items/FigureTwicpics/twig-api',
        '@ui/Figure/FigureTwicpics.twig',
      ),
    ],
    related: ['figure', 'figure-video-twicpics'],
  },
  {
    id: 'figure-video',
    title: 'FigureVideo',
    summary: 'Render responsive videos with lazy loading, sources, and captions.',
    kind: 'component',
    path: '/reference/items/FigureVideo/',
    family: 'media',
    primaryTask: 'media',
    tags: ['video', 'figure', 'responsive', 'lazy loading'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('FigureVideo', '/reference/items/FigureVideo/js-api'),
      twigSymbol(
        'FigureVideo.twig',
        '/reference/items/FigureVideo/twig-api',
        '@ui/FigureVideo/FigureVideo.twig',
      ),
    ],
    capabilities: ['lazy loading', 'multiple sources', 'placeholders'],
    related: ['figure', 'figure-video-twicpics'],
  },
  {
    id: 'figure-video-twicpics',
    title: 'FigureVideoTwicpics',
    summary: 'Deliver responsive video through TwicPics with optimized source URLs.',
    kind: 'component',
    path: '/reference/items/FigureVideoTwicpics/',
    family: 'media',
    primaryTask: 'media',
    tags: ['video', 'twicpics', 'cdn', 'responsive'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('FigureVideoTwicpics', '/reference/items/FigureVideoTwicpics/js-api'),
      twigSymbol(
        'FigureVideoTwicpics.twig',
        '/reference/items/FigureVideoTwicpics/twig-api',
        '@ui/FigureVideo/FigureVideoTwicpics.twig',
      ),
    ],
    related: ['figure-video', 'figure-twicpics'],
  },
  {
    id: 'frame',
    title: 'Frame',
    summary: 'Build server-rendered navigation frames with triggers, targets, and loaders.',
    kind: 'component',
    path: '/reference/items/Frame/',
    family: 'loading',
    primaryTask: 'loading',
    tags: ['frame', 'navigation', 'fetch', 'forms'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Frame', '/reference/items/Frame/js-api/frame'),
      uiSymbol('FrameAnchor', '/reference/items/Frame/js-api/frame-anchor'),
      uiSymbol('FrameForm', '/reference/items/Frame/js-api/frame-form'),
      uiSymbol('FrameLoader', '/reference/items/Frame/js-api/frame-loader'),
      uiSymbol('FrameTarget', '/reference/items/Frame/js-api/frame-target'),
      uiSymbol('FrameTriggerLoader', '/reference/items/Frame/js-api/frame-trigger-loader'),
      uiSymbol(
        'AbstractFrameTrigger',
        '/reference/items/Frame/js-api/abstract-frame-trigger',
        'AbstractFrameTrigger',
        'primitive',
      ),
      ...frameTypes,
    ],
    capabilities: ['anchors', 'forms', 'loaders', 'targeted replacement'],
    related: ['fetch', 'lazy-include'],
  },
  {
    id: 'hero',
    title: 'Hero',
    summary: 'Compose hero sections with media, text, actions, and flexible positioning.',
    kind: 'component',
    path: '/reference/items/Hero/',
    family: 'layout',
    primaryTask: 'layout',
    tags: ['hero', 'banner', 'layout', 'twig'],
    surfaces: ['twig'],
    packages: [twigPackage],
    status: 'stable',
    symbols: [twigSymbol('Hero.twig', '/reference/items/Hero/twig-api', '@ui/Hero/Hero.twig')],
    capabilities: ['background media', 'content positioning', 'template blocks'],
    related: ['figure'],
  },
  {
    id: 'hoverable',
    title: 'Hoverable',
    summary: 'Reflect pointer hover state for declarative styling and interactions.',
    kind: 'component',
    path: '/reference/items/Hoverable/',
    family: 'interaction',
    primaryTask: 'action',
    tags: ['hover', 'pointer', 'state', 'interaction'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('Hoverable', '/reference/items/Hoverable/js-api')],
    related: ['cursor'],
  },
  {
    id: 'icon',
    title: 'Icon',
    summary: 'Render inline SVG icons from local files or configured icon sets.',
    kind: 'component',
    path: '/reference/items/Icon/',
    family: 'media',
    primaryTask: 'media',
    tags: ['icon', 'svg', 'iconify', 'twig'],
    surfaces: ['twig'],
    packages: [twigPackage],
    status: 'stable',
    symbols: [twigSymbol('Icon.twig', '/reference/items/Icon/twig-api', '@ui/Icon/Icon.twig')],
    related: ['icon-img', 'icon-list'],
  },
  {
    id: 'icon-img',
    title: 'IconImg',
    summary: 'Render icons as image sources with optional current-color support.',
    kind: 'component',
    path: '/reference/items/IconImg/',
    family: 'media',
    primaryTask: 'media',
    tags: ['icon', 'image', 'iconify', 'twig'],
    surfaces: ['twig'],
    packages: [twigPackage],
    status: 'stable',
    symbols: [
      twigSymbol('IconImg.twig', '/reference/items/IconImg/twig-api', '@ui/Icon/IconImg.twig'),
    ],
    related: ['icon', 'icon-list'],
  },
  {
    id: 'icon-list',
    title: 'IconList',
    summary: 'Render structured lists of icons, labels, and optional actions.',
    kind: 'component',
    path: '/reference/items/IconList/',
    family: 'layout',
    primaryTask: 'layout',
    tags: ['icon', 'list', 'actions', 'twig'],
    surfaces: ['twig'],
    packages: [twigPackage],
    status: 'stable',
    symbols: [
      twigSymbol(
        'IconList.twig',
        '/reference/items/IconList/twig-api',
        '@ui/IconList/IconList.twig',
      ),
    ],
    related: ['icon'],
  },
  {
    id: 'image-grid',
    title: 'ImageGrid',
    summary: 'Arrange image collections in a reusable Twig grid composition.',
    kind: 'component',
    path: '/reference/items/ImageGrid/',
    family: 'media',
    primaryTask: 'layout',
    tags: ['image', 'grid', 'gallery', 'twig'],
    surfaces: ['twig'],
    packages: [twigPackage],
    status: 'stable',
    symbols: [
      twigSymbol(
        'ImageGrid.twig',
        '/reference/items/ImageGrid/twig-api',
        '@ui/ImageGrid/ImageGrid.twig',
      ),
    ],
    related: ['figure'],
  },
  {
    id: 'in-view',
    title: 'InView',
    summary: 'Observe when an element enters or leaves the viewport.',
    kind: 'primitive',
    path: '/reference/items/InView/',
    family: 'visibility',
    primaryTask: 'animation',
    tags: ['intersection observer', 'viewport', 'visibility', 'events'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('InView', '/reference/items/InView/js-api', 'InView', 'primitive')],
    related: ['in-view-once', 'scroll-reveal', 'sentinel'],
  },
  {
    id: 'in-view-once',
    title: 'InViewOnce',
    summary: 'Observe the first time an element enters the viewport.',
    kind: 'primitive',
    path: '/reference/items/InViewOnce/',
    family: 'visibility',
    primaryTask: 'animation',
    tags: ['intersection observer', 'viewport', 'visibility', 'once'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('InViewOnce', '/reference/items/InViewOnce/js-api', 'InViewOnce', 'primitive'),
    ],
    related: ['in-view', 'scroll-reveal'],
  },
  {
    id: 'indexable',
    title: 'Indexable',
    summary: 'Manage a bounded active index as a reusable headless behavior.',
    kind: 'primitive',
    path: '/reference/items/Indexable/',
    family: 'state',
    primaryTask: 'navigation',
    tags: ['index', 'state', 'navigation', 'headless'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('Indexable', '/reference/items/Indexable/js-api', 'Indexable', 'primitive')],
    related: ['slider', 'with-index'],
  },
  {
    id: 'large-text',
    title: 'LargeText',
    summary: 'Scale and repeat oversized text to fill its available width.',
    kind: 'component',
    path: '/reference/items/LargeText/',
    family: 'layout',
    primaryTask: 'layout',
    tags: ['text', 'typography', 'responsive', 'layout'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('LargeText', '/reference/items/LargeText/js-api'),
      twigSymbol(
        'LargeText.twig',
        '/reference/items/LargeText/twig-api',
        '@ui/LargeText/LargeText.twig',
      ),
    ],
  },
  {
    id: 'lazy-include',
    title: 'LazyInclude',
    summary: 'Load and inject remote markup when an include enters the viewport.',
    kind: 'component',
    path: '/reference/items/LazyInclude/',
    family: 'loading',
    primaryTask: 'loading',
    tags: ['lazy loading', 'include', 'fetch', 'html'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('LazyInclude', '/reference/items/LazyInclude/js-api')],
    related: ['fetch', 'frame', 'prefetch'],
  },
  {
    id: 'mapbox-map',
    title: 'MapboxMap',
    summary: 'Compose declarative Mapbox maps from maps, controls, data, markers, and clusters.',
    kind: 'component',
    path: '/reference/items/MapboxMap/',
    family: 'maps',
    primaryTask: 'maps',
    tags: ['mapbox', 'map', 'markers', 'clusters'],
    surfaces: ['js'],
    packages: [mapboxPackage],
    status: 'stable',
    symbols: [
      mapboxSymbol('MapboxMap', '/reference/items/MapboxMap/js-api#mapboxmap'),
      mapboxSymbol('MapboxMarker', '/reference/items/MapboxMap/js-api#mapboxmarker'),
      mapboxSymbol('MapboxPopup', '/reference/items/MapboxMap/js-api#mapboxpopup'),
      mapboxSymbol(
        'MapboxNavigationControl',
        '/reference/items/MapboxMap/js-api#mapboxnavigationcontrol',
      ),
      mapboxSymbol(
        'MapboxGeolocateControl',
        '/reference/items/MapboxMap/js-api#mapboxgeolocatecontrol',
      ),
      mapboxSymbol(
        'MapboxFullscreenControl',
        '/reference/items/MapboxMap/js-api#mapboxfullscreencontrol',
      ),
      mapboxSymbol('MapboxGeocoder', '/reference/items/MapboxMap/js-api#mapboxgeocoder'),
      mapboxSymbol('MapboxSource', '/reference/items/MapboxMap/js-api#mapboxsource'),
      mapboxSymbol('MapboxLayer', '/reference/items/MapboxMap/js-api#mapboxlayer'),
      mapboxSymbol('MapboxImage', '/reference/items/MapboxMap/js-api#mapboximage'),
      mapboxSymbol('MapboxImages', '/reference/items/MapboxMap/js-api#mapboximages'),
      mapboxSymbol('MapboxCluster', '/reference/items/MapboxMap/js-api#mapboxcluster'),
      mapboxSymbol('MapboxClusterItem', '/reference/items/MapboxMap/js-api#mapboxclusteritem'),
      mapboxSymbol(
        'AbstractMapboxMapChild',
        '/reference/items/MapboxMap/js-api#abstractmapboxmapchild',
        'primitive',
      ),
      mapboxSymbol(
        'AbstractMapboxControl',
        '/reference/items/MapboxMap/js-api#abstractmapboxcontrol',
        'primitive',
      ),
      mapboxSymbol(
        'provideMapboxGl',
        '/reference/items/MapboxMap/js-api#providing-the-mapbox-gl-dependency',
        'helper',
      ),
      mapboxSymbol(
        'provideMapboxGeocoder',
        '/reference/items/MapboxMap/js-api#providing-the-mapbox-gl-dependency',
        'helper',
      ),
      mapboxSymbol(
        'resolveMapboxGl',
        '/reference/items/MapboxMap/js-api#providing-the-mapbox-gl-dependency',
        'helper',
      ),
      mapboxSymbol(
        'resolveMapboxGeocoder',
        '/reference/items/MapboxMap/js-api#providing-the-mapbox-gl-dependency',
        'helper',
      ),
      mapboxSymbol(
        'MapboxGl',
        '/reference/items/MapboxMap/js-api#providing-the-mapbox-gl-dependency',
        'type',
      ),
      mapboxSymbol(
        'MapboxGeocoderControl',
        '/reference/items/MapboxMap/js-api#providing-the-mapbox-gl-dependency',
        'type',
      ),
      mapboxSymbol(
        'MapboxGeocoderConstructor',
        '/reference/items/MapboxMap/js-api#providing-the-mapbox-gl-dependency',
        'type',
      ),
    ],
    capabilities: ['clusters', 'controls', 'markers', 'sources and layers'],
    related: ['mapbox-static-map', 'store-locator'],
  },
  {
    id: 'mapbox-static-map',
    title: 'MapboxStaticMap',
    summary: 'Render Mapbox Static Images API URLs without loading an interactive map.',
    kind: 'component',
    path: '/reference/items/MapboxStaticMap/',
    family: 'maps',
    primaryTask: 'maps',
    tags: ['mapbox', 'static map', 'image', 'twig'],
    surfaces: ['twig'],
    packages: [twigPackage],
    status: 'stable',
    symbols: [
      twigSymbol(
        'MapboxStaticMap.twig',
        '/reference/items/MapboxStaticMap/twig-api',
        '@ui/MapboxStaticMap/MapboxStaticMap.twig',
      ),
    ],
    related: ['mapbox-map'],
  },
  {
    id: 'menu',
    title: 'Menu',
    summary: 'Compose accessible menus from toggle buttons and nested lists.',
    kind: 'component',
    path: '/reference/items/Menu/',
    family: 'navigation',
    primaryTask: 'navigation',
    tags: ['menu', 'navigation', 'dropdown', 'burger'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Menu', '/reference/items/Menu/js-api'),
      uiSymbol('MenuBtn', '/reference/items/Menu/js-api'),
      uiSymbol('MenuList', '/reference/items/Menu/js-api'),
    ],
    capabilities: ['dropdowns', 'nested lists', 'responsive menus'],
    related: ['action', 'click-outside'],
  },
  {
    id: 'modal',
    title: 'Modal',
    summary: 'Open modal overlays with optional transition-aware behavior.',
    kind: 'component',
    path: '/reference/items/Modal/',
    family: 'overlay',
    primaryTask: 'overlay',
    tags: ['modal', 'overlay', 'dialog', 'deprecated'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'deprecated',
    symbols: [
      uiSymbol('Modal', '/reference/items/Modal/js-api', 'Modal', 'component', 'deprecated'),
      uiSymbol(
        'ModalWithTransition',
        '/reference/items/Modal/js-api',
        'ModalWithTransition',
        'component',
        'deprecated',
      ),
      twigSymbol(
        'Modal.twig',
        '/reference/items/Modal/twig-api',
        '@ui/Modal/Modal.twig',
        'deprecated',
      ),
      twigSymbol(
        'StyledModal.twig',
        '/reference/items/Modal/twig-api',
        '@ui/Modal/StyledModal.twig',
        'deprecated',
      ),
    ],
    related: ['dialog', 'panel'],
  },
  {
    id: 'motion',
    title: 'Motion',
    summary: 'Animate elements declaratively with Motion and drive the playback from interactions.',
    kind: 'component',
    path: '/reference/items/Motion/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['motion', 'animation', 'spring', 'playback'],
    surfaces: ['js'],
    packages: [motionPackage],
    status: 'stable',
    symbols: [
      motionSymbol('Motion', '/reference/items/Motion/js-api#motion'),
      motionSymbol(
        'MotionScrollTimeline',
        '/reference/items/Motion/js-api#motionscrolltimeline',
      ),
      motionSymbol('MotionSequence', '/reference/items/Motion/js-api#motionsequence'),
      motionSymbol(
        'provideMotion',
        '/reference/items/Motion/js-api#providing-the-motion-dependency',
        'helper',
      ),
      motionSymbol(
        'resolveMotion',
        '/reference/items/Motion/js-api#providing-the-motion-dependency',
        'helper',
      ),
      motionSymbol(
        'MotionModule',
        '/reference/items/Motion/js-api#providing-the-motion-dependency',
        'type',
      ),
    ],
    capabilities: ['enter animations', 'spring physics', 'imperative playback'],
    related: ['action', 'transition', 'scroll-reveal'],
  },
  {
    id: 'panel',
    title: 'Panel',
    summary: 'Open a positioned off-canvas panel from an overlay.',
    kind: 'component',
    path: '/reference/items/Panel/',
    family: 'overlay',
    primaryTask: 'overlay',
    tags: ['panel', 'drawer', 'overlay', 'deprecated'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'deprecated',
    symbols: [
      uiSymbol('Panel', '/reference/items/Panel/js-api', 'Panel', 'component', 'deprecated'),
      twigSymbol(
        'Panel.twig',
        '/reference/items/Panel/twig-api',
        '@ui/Panel/Panel.twig',
        'deprecated',
      ),
      twigSymbol(
        'StyledPanel.twig',
        '/reference/items/Panel/twig-api',
        '@ui/Panel/StyledPanel.twig',
        'deprecated',
      ),
    ],
    related: ['dialog', 'modal'],
  },
  {
    id: 'prefetch',
    title: 'Prefetch',
    summary: 'Prefetch links through reusable hover and visibility strategies.',
    kind: 'component',
    path: '/reference/items/Prefetch/',
    family: 'loading',
    primaryTask: 'loading',
    tags: ['prefetch', 'links', 'hover', 'visibility'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol(
        'AbstractPrefetch',
        '/reference/items/Prefetch/js-api',
        'AbstractPrefetch',
        'primitive',
      ),
      uiSymbol('PrefetchWhenOver', '/reference/items/Prefetch/js-api'),
      uiSymbol('PrefetchWhenVisible', '/reference/items/Prefetch/js-api'),
    ],
    capabilities: ['custom strategies', 'hover prefetch', 'visibility prefetch'],
    related: ['lazy-include'],
  },
  {
    id: 'reinsurance',
    title: 'Reinsurance',
    summary: 'Render reassurance lists with icons and an optional mobile slider layout.',
    kind: 'component',
    path: '/reference/items/Reinsurance/',
    family: 'layout',
    primaryTask: 'layout',
    tags: ['reassurance', 'list', 'icons', 'twig'],
    surfaces: ['twig'],
    packages: [twigPackage],
    status: 'stable',
    symbols: [
      twigSymbol(
        'Reinsurance.twig',
        '/reference/items/Reinsurance/twig-api',
        '@ui/Reinsurance/Reinsurance.twig',
      ),
    ],
    capabilities: ['mobile slider', 'template blocks'],
  },
  {
    id: 'scroll-animation',
    title: 'ScrollAnimation',
    summary: 'Build timeline-driven scroll animations from parent and target components.',
    kind: 'component',
    path: '/reference/items/ScrollAnimation/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['scroll', 'animation', 'timeline', 'parallax'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol(
        'AbstractScrollAnimation',
        '/reference/items/ScrollAnimation/js-api',
        'AbstractScrollAnimation',
        'primitive',
        'deprecated',
      ),
      uiSymbol(
        'ScrollAnimation',
        '/reference/items/ScrollAnimation/js-api#scrollanimation-deprecated',
        'ScrollAnimation',
        'component',
        'deprecated',
      ),
      uiSymbol(
        'ScrollAnimationChild',
        '/reference/items/ScrollAnimation/js-api',
        'ScrollAnimationChild',
        'component',
        'deprecated',
      ),
      uiSymbol(
        'ScrollAnimationChildWithEase',
        '/reference/items/ScrollAnimation/js-api',
        'ScrollAnimationChildWithEase',
        'component',
        'deprecated',
      ),
      uiSymbol(
        'ScrollAnimationParent',
        '/reference/items/ScrollAnimation/js-api',
        'ScrollAnimationParent',
        'component',
        'deprecated',
      ),
      uiSymbol(
        'ScrollAnimationTarget',
        '/reference/items/ScrollAnimation/js-api#scrollanimationtarget',
      ),
      uiSymbol(
        'ScrollAnimationTimeline',
        '/reference/items/ScrollAnimation/js-api#scrollanimationtimeline',
      ),
      uiSymbol(
        'ScrollAnimationWithEase',
        '/reference/items/ScrollAnimation/js-api',
        'ScrollAnimationWithEase',
        'component',
        'deprecated',
      ),
    ],
    aliases: ['scroll timeline', 'parallax'],
    capabilities: ['damping', 'keyframes', 'offsets', 'staggering'],
    related: ['animation-scroll-with-ease', 'scroll-reveal', 'with-scroll-animation-debug'],
  },
  {
    id: 'scroll-reveal',
    title: 'ScrollReveal',
    summary: 'Reveal elements as they enter the viewport, once or repeatedly.',
    kind: 'component',
    path: '/reference/items/ScrollReveal/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['scroll', 'reveal', 'intersection observer', 'animation'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('ScrollReveal', '/reference/items/ScrollReveal/js-api')],
    related: ['in-view', 'in-view-once', 'scroll-animation'],
  },
  {
    id: 'sentinel',
    title: 'Sentinel',
    summary: 'Observe a boundary element to coordinate scroll-based state.',
    kind: 'primitive',
    path: '/reference/items/Sentinel/',
    family: 'visibility',
    primaryTask: 'timing',
    tags: ['sentinel', 'intersection observer', 'scroll', 'headless'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('Sentinel', '/reference/items/Sentinel/', 'Sentinel', 'primitive')],
    related: ['in-view'],
  },
  {
    id: 'slider',
    title: 'Slider',
    summary: 'Compose indexed sliders from items, controls, dots, drag, and progress.',
    kind: 'component',
    path: '/reference/items/Slider/',
    family: 'carousel',
    primaryTask: 'navigation',
    tags: ['slider', 'carousel', 'drag', 'navigation'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol(
        'AbstractSliderChild',
        '/reference/items/Slider/js-api/',
        'AbstractSliderChild',
        'primitive',
      ),
      uiSymbol('Slider', '/reference/items/Slider/js-api/slider'),
      uiSymbol('SliderBtn', '/reference/items/Slider/js-api/slider-btn'),
      uiSymbol('SliderCount', '/reference/items/Slider/js-api/slider-count'),
      uiSymbol('SliderDots', '/reference/items/Slider/js-api/slider-dots'),
      uiSymbol('SliderDrag', '/reference/items/Slider/js-api/slider-drag'),
      uiSymbol('SliderItem', '/reference/items/Slider/js-api/slider-item'),
      uiSymbol('SliderProgress', '/reference/items/Slider/js-api/slider-progress'),
    ],
    capabilities: ['dragging', 'dots', 'index count', 'progress'],
    related: ['carousel', 'indexable'],
  },
  {
    id: 'sticky',
    title: 'Sticky',
    summary: 'Keep content sticky while exposing its active position state.',
    kind: 'component',
    path: '/reference/items/Sticky/',
    family: 'layout',
    primaryTask: 'layout',
    tags: ['sticky', 'position', 'scroll', 'layout'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Sticky', '/reference/items/Sticky/js-api'),
      twigSymbol('Sticky.twig', '/reference/items/Sticky/twig-api', '@ui/Sticky/Sticky.twig'),
    ],
  },
  {
    id: 'store-locator',
    title: 'StoreLocator',
    summary: 'Orchestrate a Mapbox cluster into a searchable, selectable store locator.',
    kind: 'component',
    path: '/reference/items/StoreLocator/',
    family: 'maps',
    primaryTask: 'maps',
    tags: ['mapbox', 'store locator', 'cluster', 'geocoder'],
    surfaces: ['js'],
    packages: [mapboxPackage],
    status: 'stable',
    symbols: [mapboxSymbol('StoreLocator', '/reference/items/StoreLocator/js-api#storelocator')],
    capabilities: ['bounds filtering', 'distance sorting', 'selection'],
    related: ['mapbox-map'],
  },
  {
    id: 'tabs',
    title: 'Tabs',
    summary: 'Build accessible tab lists and panels with synchronized active state.',
    kind: 'component',
    path: '/reference/items/Tabs/',
    family: 'navigation',
    primaryTask: 'navigation',
    tags: ['tabs', 'panels', 'navigation', 'accessibility'],
    surfaces: ['js', 'twig'],
    packages: [uiPackage, twigPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Tabs', '/reference/items/Tabs/js-api'),
      twigSymbol('Tabs.twig', '/reference/items/Tabs/twig-api', '@ui/Tabs/Tabs.twig'),
    ],
    capabilities: ['keyboard navigation', 'panels'],
    related: ['accordion', 'indexable'],
  },
  {
    id: 'timer',
    title: 'Timer',
    summary: 'Drive elapsed time and progress without prescribing rendered controls.',
    kind: 'primitive',
    path: '/reference/items/Timer/',
    family: 'timing',
    primaryTask: 'timing',
    tags: ['timer', 'progress', 'duration', 'headless'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Timer', '/reference/items/Timer/js-api', 'Timer', 'primitive'),
      uiSymbol('TimerProgress', '/reference/items/Timer/js-api', 'TimerProgress', 'primitive'),
    ],
    capabilities: ['continuous progress', 'duration'],
  },
  {
    id: 'toaster',
    title: 'Toaster',
    summary: 'Announce toasts from live regions with pausable auto-dismiss and animated stacking.',
    kind: 'component',
    path: '/reference/items/Toaster/',
    family: 'overlay',
    primaryTask: 'overlay',
    tags: ['toast', 'notification', 'snackbar', 'aria-live', 'overlay'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Toaster', '/reference/items/Toaster/js-api'),
      uiSymbol('Toast', '/reference/items/Toaster/js-api'),
    ],
    capabilities: ['aria-live regions', 'pausable auto-dismiss', 'batched view transitions'],
    related: ['action', 'dialog', 'timer', 'view-transition'],
  },
  {
    id: 'track',
    title: 'Track',
    summary: 'Declare provider-agnostic analytics events and inherited tracking context.',
    kind: 'component',
    path: '/reference/items/Track/',
    family: 'tracking',
    primaryTask: 'tracking',
    tags: ['analytics', 'tracking', 'events', 'shopify'],
    surfaces: ['js', 'twig', 'liquid'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Track', '/reference/items/Track/js-api'),
      uiSymbol('TrackContext', '/reference/items/Track/js-api'),
      uiSymbol('TrackShopify', '/reference/items/Track/js-api'),
    ],
    capabilities: ['click tracking', 'context', 'custom events', 'impression tracking'],
  },
  {
    id: 'transition',
    title: 'Transition',
    summary: 'Coordinate enter and leave transitions as a reusable headless primitive.',
    kind: 'primitive',
    path: '/reference/items/Transition/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['transition', 'enter', 'leave', 'animation'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('Transition', '/reference/items/Transition/js-api', 'Transition', 'primitive'),
    ],
    related: ['view-transition', 'with-transition'],
  },
  {
    id: 'view-transition',
    title: 'ViewTransition',
    summary: 'Coordinate component state with the native View Transitions API.',
    kind: 'primitive',
    path: '/reference/items/ViewTransition/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['view transition', 'animation', 'native api', 'progressive enhancement'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol(
        'ViewTransition',
        '/reference/items/ViewTransition/js-api',
        'ViewTransition',
        'primitive',
      ),
    ],
    related: ['transition', 'view-transition-helper'],
  },
  {
    id: 'with-transition',
    title: 'withTransition',
    summary: 'Decorate a component with reusable enter and leave transition behavior.',
    kind: 'decorator',
    path: '/reference/items/withTransition/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['decorator', 'transition', 'enter', 'leave'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('withTransition', '/reference/items/withTransition/', 'withTransition', 'decorator'),
    ],
    related: ['transition'],
  },
  {
    id: 'with-index',
    title: 'withIndex',
    summary: 'Decorate a component with reusable indexed state and navigation methods.',
    kind: 'decorator',
    path: '/reference/items/withIndex/',
    family: 'state',
    primaryTask: 'navigation',
    tags: ['decorator', 'index', 'state', 'navigation'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [uiSymbol('withIndex', '/reference/items/withIndex/', 'withIndex', 'decorator')],
    related: ['indexable'],
  },
  {
    id: 'with-deprecation',
    title: 'withDeprecation',
    summary: 'Decorate a component to emit a development-time deprecation notice.',
    kind: 'decorator',
    path: '/reference/items/withDeprecation/',
    family: 'development',
    tags: ['decorator', 'deprecation', 'migration', 'development'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol(
        'withDeprecation',
        '/reference/items/withDeprecation/',
        'withDeprecation',
        'decorator',
      ),
    ],
  },
  {
    id: 'with-scroll-animation-debug',
    title: 'withScrollAnimationDebug',
    summary: 'Decorate scroll timelines with tree-shakable visual debugging markers.',
    kind: 'decorator',
    path: '/reference/items/withScrollAnimationDebug/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['decorator', 'scroll', 'animation', 'debug'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol(
        'withScrollAnimationDebug',
        '/reference/items/withScrollAnimationDebug/',
        'withScrollAnimationDebug',
        'decorator',
      ),
    ],
    related: ['scroll-animation'],
  },
  {
    id: 'animation-scroll-with-ease',
    title: 'animationScrollWithEase',
    summary: 'Apply legacy easing behavior to a scroll animation class.',
    kind: 'decorator',
    path: '/reference/items/animationScrollWithEase/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['helper', 'scroll', 'animation', 'deprecated'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'deprecated',
    symbols: [
      uiSymbol(
        'animationScrollWithEase',
        '/reference/items/animationScrollWithEase/',
        'animationScrollWithEase',
        'decorator',
        'deprecated',
      ),
    ],
    related: ['scroll-animation'],
  },
  {
    id: 'view-transition-helper',
    title: 'viewTransition',
    summary: 'Batch DOM updates into serialized native view transitions with a safe fallback.',
    kind: 'helper',
    path: '/reference/items/view-transition-helper/',
    family: 'animation',
    primaryTask: 'animation',
    tags: ['helper', 'view transition', 'batching', 'progressive enhancement'],
    surfaces: ['js'],
    packages: [uiPackage],
    status: 'stable',
    symbols: [
      uiSymbol('viewTransition', '/reference/items/view-transition-helper/', 'scheduler', 'helper'),
    ],
    aliases: ['scheduler'],
    related: ['view-transition'],
  },
] satisfies ReferenceCatalogEntry[];

function includesAny<T>(values: T[], selected?: T[]): boolean {
  return !selected?.length || selected.some((value) => values.includes(value));
}

export function filterCatalogEntries(
  entries: ReferenceCatalogEntry[] = referenceCatalog,
  filters: ReferenceCatalogFilters = {},
): ReferenceCatalogEntry[] {
  const query = filters.query?.trim().toLocaleLowerCase();

  return entries.filter((entry) => {
    const searchable = [
      entry.title,
      entry.summary,
      entry.family,
      entry.primaryTask,
      ...entry.tags,
      ...(entry.aliases ?? []),
      ...entry.symbols.map((symbol) => symbol.name),
      ...publicContractSymbols
        .filter((symbol) => symbol.href.startsWith(entry.path))
        .map((symbol) => symbol.name),
    ]
      .filter(Boolean)
      .join(' ')
      .toLocaleLowerCase();

    return (
      (!query || searchable.includes(query)) &&
      (!filters.kinds?.length || filters.kinds.includes(entry.kind)) &&
      (!filters.families?.length || (!!entry.family && filters.families.includes(entry.family))) &&
      includesAny(entry.tags, filters.tags) &&
      includesAny(entry.surfaces, filters.surfaces) &&
      includesAny(entry.packages, filters.packages) &&
      (!filters.statuses?.length || filters.statuses.includes(entry.status))
    );
  });
}

export function sortCatalogEntries(
  entries: ReferenceCatalogEntry[] = referenceCatalog,
): ReferenceCatalogEntry[] {
  return [...entries].sort((left, right) => left.title.localeCompare(right.title));
}

export function groupCatalogEntries(
  entries: ReferenceCatalogEntry[] = referenceCatalog,
  group: ReferenceCatalogGroup = 'kind',
): Record<string, ReferenceCatalogEntry[]> {
  const grouped: Record<string, ReferenceCatalogEntry[]> = {};

  for (const entry of entries) {
    const keys =
      group === 'package'
        ? entry.packages
        : group === 'surface'
          ? entry.surfaces
          : [entry[group] ?? 'other'];

    for (const key of keys) {
      (grouped[key] ??= []).push(entry);
    }
  }

  return grouped;
}

export function getReferenceSymbols(
  entries: ReferenceCatalogEntry[] = referenceCatalog,
): ReferenceSymbol[] {
  return [
    ...entries.flatMap((entry) =>
      entry.symbols.map((symbol) => ({
        ...symbol,
        status: symbol.status ?? entry.status,
      })),
    ),
    ...publicContractSymbols,
  ];
}

export const allReferenceSymbols = getReferenceSymbols();
