import type { ReferenceSymbol } from './types';

/**
 * Public type and constant contracts exported from the package root barrels.
 * The reference validator compares this list with TypeScript's module graph so
 * newly exported contracts cannot be omitted silently.
 */
export const publicContractSymbols = [
  {
    name: 'AbstractCarouselChildProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'AbstractCarouselComponentProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'AbstractFrameTriggerProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Frame/js-api/',
    status: 'stable',
  },
  {
    name: 'AbstractPrefetchProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Prefetch/js-api',
    status: 'stable',
  },
  {
    name: 'AbstractScrollAnimationProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ScrollAnimation/js-api',
    status: 'deprecated',
  },
  {
    name: 'AbstractSliderChildProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'AccordionItemProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Accordion/',
    status: 'stable',
  },
  {
    name: 'ActionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Action/js-api',
    status: 'stable',
  },
  {
    name: 'AnchorNavLinkProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/AnchorNav/js-api',
    status: 'stable',
  },
  {
    name: 'AnchorNavProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/AnchorNav/js-api',
    status: 'stable',
  },
  {
    name: 'AnchorScrollToProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/AnchorScrollTo/js-api',
    status: 'stable',
  },
  {
    name: 'AnimationScrollWithEaseInterface',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/animationScrollWithEase/',
    status: 'deprecated',
  },
  {
    name: 'AnimationScrollWithEaseProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/animationScrollWithEase/',
    status: 'deprecated',
  },
  {
    name: 'CarouselBtnProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselDragProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselItemProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselStore',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselWrapperProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CircularMarqueeProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/CircularMarquee/',
    status: 'stable',
  },
  {
    name: 'ClickOutsideProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ClickOutside/js-api',
    status: 'stable',
  },
  {
    name: 'CursorProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Cursor/js-api',
    status: 'stable',
  },
  {
    name: 'DataBindProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataBind/js-api',
    status: 'stable',
  },
  {
    name: 'DataComputedProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataComputed/js-api',
    status: 'stable',
  },
  {
    name: 'DataEffectProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataEffect/js-api',
    status: 'stable',
  },
  {
    name: 'DataModelProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataModel/js-api',
    status: 'stable',
  },
  {
    name: 'DataScopeProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DataValue',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DeprecationInterface',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withDeprecation/',
    status: 'stable',
  },
  {
    name: 'DeprecationProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withDeprecation/',
    status: 'stable',
  },
  {
    name: 'DialogProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Dialog/js-api',
    status: 'stable',
  },
  {
    name: 'DisclosureGroupProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Disclosure/js-api',
    status: 'stable',
  },
  {
    name: 'DisclosureProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Disclosure/js-api',
    status: 'stable',
  },
  {
    name: 'DomUpdateRunner',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'DomUpdateTransitioner',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'DraggableProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Draggable/js-api',
    status: 'stable',
  },
  {
    name: 'FetchConstructor',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'FetchProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'FetchUpdateWrapper',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'FetchShopifyPartialConstructor',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FetchShopifyPartial/js-api',
    status: 'preview',
  },
  {
    name: 'FetchShopifyPartialProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FetchShopifyPartial/js-api',
    status: 'preview',
  },
  {
    name: 'FetchShopifySectionConstructor',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FetchShopifySection/js-api',
    status: 'stable',
  },
  {
    name: 'FetchShopifySectionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FetchShopifySection/js-api',
    status: 'stable',
  },
  {
    name: 'FigureProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Figure/js-api',
    status: 'stable',
  },
  {
    name: 'FigureShopifyProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FigureShopify/js-api',
    status: 'stable',
  },
  {
    name: 'FigureTwicpicsProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FigureTwicpics/js-api',
    status: 'stable',
  },
  {
    name: 'FigureVideoProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FigureVideo/js-api',
    status: 'stable',
  },
  {
    name: 'FigureVideoTwicpicsProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FigureVideoTwicpics/js-api',
    status: 'stable',
  },
  {
    name: 'FrameAnchorProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Frame/js-api/',
    status: 'stable',
  },
  {
    name: 'FrameFormProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Frame/js-api/',
    status: 'stable',
  },
  {
    name: 'FrameLoaderProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Frame/js-api/',
    status: 'stable',
  },
  {
    name: 'FrameProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Frame/js-api/',
    status: 'stable',
  },
  {
    name: 'FrameTargetProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Frame/js-api/',
    status: 'stable',
  },
  {
    name: 'FrameTriggerLoaderProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Frame/js-api/',
    status: 'stable',
  },
  {
    name: 'HoverableProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Hoverable/js-api',
    status: 'stable',
  },
  {
    name: 'IndexableBoundary',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withIndex/',
    status: 'stable',
  },
  {
    name: 'IndexableInstructions',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withIndex/',
    status: 'stable',
  },
  {
    name: 'IndexableInterface',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withIndex/',
    status: 'stable',
  },
  {
    name: 'IndexableProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withIndex/',
    status: 'stable',
  },
  {
    name: 'LargeTextProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/LargeText/js-api',
    status: 'stable',
  },
  {
    name: 'LazyIncludeProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/LazyInclude/js-api',
    status: 'stable',
  },
  {
    name: 'MenuListProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Menu/js-api',
    status: 'stable',
  },
  {
    name: 'MenuProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Menu/js-api',
    status: 'stable',
  },
  {
    name: 'ModalProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Modal/js-api',
    status: 'deprecated',
  },
  {
    name: 'PanelProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Panel/js-api',
    status: 'deprecated',
  },
  {
    name: 'ScrollAnimationChildProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ScrollAnimation/js-api',
    status: 'deprecated',
  },
  {
    name: 'ScrollAnimationParentProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ScrollAnimation/js-api',
    status: 'deprecated',
  },
  {
    name: 'ScrollAnimationProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ScrollAnimation/js-api',
    status: 'deprecated',
  },
  {
    name: 'ScrollAnimationTargetProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ScrollAnimation/js-api',
    status: 'stable',
  },
  {
    name: 'ScrollAnimationTimelineProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ScrollAnimation/js-api',
    status: 'stable',
  },
  {
    name: 'ScrollRevealProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ScrollReveal/js-api',
    status: 'stable',
  },
  {
    name: 'SliderBtnProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'SliderCountProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'SliderDotsProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'SliderDragProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'SliderItemProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'SliderModes',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'SliderProgressProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'SliderProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'SliderStore',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Slider/js-api/',
    status: 'stable',
  },
  {
    name: 'StickyProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Sticky/js-api',
    status: 'stable',
  },
  {
    name: 'TabsProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Tabs/js-api',
    status: 'stable',
  },
  {
    name: 'TargetProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Action/js-api',
    status: 'stable',
  },
  {
    name: 'TimerProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Timer/js-api',
    status: 'stable',
  },
  {
    name: 'ToastProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Toaster/js-api',
    status: 'stable',
  },
  {
    name: 'ToasterProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Toaster/js-api',
    status: 'stable',
  },
  {
    name: 'ToasterShowOptions',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Toaster/js-api',
    status: 'stable',
  },
  {
    name: 'TrackContextProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Track/js-api',
    status: 'stable',
  },
  {
    name: 'TrackProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Track/js-api',
    status: 'stable',
  },
  {
    name: 'TrackShopifyProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Track/js-api',
    status: 'stable',
  },
  {
    name: 'TransitionConstructor',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Transition/js-api',
    status: 'stable',
  },
  {
    name: 'TransitionInterface',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withTransition/',
    status: 'stable',
  },
  {
    name: 'TransitionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withTransition/',
    status: 'stable',
  },
  {
    name: 'ViewTransitionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ViewTransition/js-api',
    status: 'stable',
  },
  {
    name: 'WithScrollAnimationDebugInterface',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withScrollAnimationDebug/',
    status: 'stable',
  },
  {
    name: 'WithScrollAnimationDebugProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withScrollAnimationDebug/',
    status: 'stable',
  },
  {
    name: 'AbstractMapboxControlProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'AbstractMapboxMapChildProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MAPBOX_CLUSTER_CONNECTED',
    kind: 'constant',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MAPBOX_MAP_CONNECTED',
    kind: 'constant',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxClusterItemProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxClusterProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxFullscreenControlProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxGeocoderProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxGeolocateControlProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxImageProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxImagesProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxLayerProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxMapProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxMarkerProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxNavigationControlProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxPopupProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxSourceProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'StoreLocatorProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/StoreLocator/js-api',
    status: 'stable',
  },
  {
    name: 'MotionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-motion',
    importPath: '@studiometa/ui-motion',
    href: '/reference/items/Motion/js-api',
    status: 'stable',
  },
  {
    name: 'MotionScrollTimelineProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-motion',
    importPath: '@studiometa/ui-motion',
    href: '/reference/items/Motion/js-api',
    status: 'stable',
  },
  {
    name: 'MotionSequenceProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-motion',
    importPath: '@studiometa/ui-motion',
    href: '/reference/items/Motion/js-api',
    status: 'stable',
  },
  {
    name: 'MotionViewProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-motion',
    importPath: '@studiometa/ui-motion',
    href: '/reference/items/Motion/js-api',
    status: 'stable',
  },
] satisfies ReferenceSymbol[];
