import type { ReferenceSymbol } from './types';

/**
 * Public type and constant contracts exported from the package root barrels.
 * The reference validator compares this list with TypeScript's module graph so
 * newly exported contracts cannot be omitted silently.
 */
export const publicContractSymbols = [
  {
    name: 'AbstractFigureDynamicProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Figure/js-api',
    status: 'stable',
  },
  {
    name: 'AbstractFigureProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Figure/js-api',
    status: 'stable',
  },
  {
    name: 'AbstractPrefetchProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Prefetch/js-api',
    status: 'stable',
  },
  {
    name: 'AbstractTrackProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Track/js-api',
    status: 'stable',
  },
  {
    name: 'ActionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Action/js-api',
    status: 'stable',
  },
  {
    name: 'ActionTarget',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Action/js-api',
    status: 'stable',
  },
  {
    name: 'AnchorNavLinkProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/AnchorNav/js-api',
    status: 'stable',
  },
  {
    name: 'AnchorNavProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/AnchorNav/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselApi',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselBtnProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselContext',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselCountProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselDotsProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselDragProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselPlayProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselProgressProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselScrollPosition',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselState',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CarouselThumbnailsProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Carousel/js-api',
    status: 'stable',
  },
  {
    name: 'CircularMarqueeProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/CircularMarquee/',
    status: 'stable',
  },
  {
    name: 'CursorProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Cursor/js-api',
    status: 'stable',
  },
  {
    name: 'DataBindOptions',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataBind/js-api',
    status: 'stable',
  },
  {
    name: 'DataBindProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataBind/js-api',
    status: 'stable',
  },
  {
    name: 'DataComputedProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataComputed/js-api',
    status: 'stable',
  },
  {
    name: 'DataControlContext',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DataControlMember',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DataEffectProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataEffect/js-api',
    status: 'stable',
  },
  {
    name: 'DataExpression',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DataModelProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataModel/js-api',
    status: 'stable',
  },
  {
    name: 'DataRegistryContext',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DataRegistryOptions',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DataScopeMember',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DataScopeProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DataUpdate',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DataValue',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/DataScope/js-api',
    status: 'stable',
  },
  {
    name: 'DeferProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Defer/js-api',
    status: 'stable',
  },
  {
    name: 'DeprecationInterface',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withDeprecation/',
    status: 'stable',
  },
  {
    name: 'DeprecationProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withDeprecation/',
    status: 'stable',
  },
  {
    name: 'DialogProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Dialog/js-api',
    status: 'stable',
  },
  {
    name: 'DisclosureGroupProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Disclosure/js-api',
    status: 'stable',
  },
  {
    name: 'DisclosureProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Disclosure/js-api',
    status: 'stable',
  },
  {
    name: 'DraggablePosition',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Draggable/js-api',
    status: 'stable',
  },
  {
    name: 'DraggableProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Draggable/js-api',
    status: 'stable',
  },
  {
    name: 'EFFECT_ARGUMENTS',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Action/js-api',
    status: 'stable',
  },
  {
    name: 'EffectFunction',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Action/js-api',
    status: 'stable',
  },
  {
    name: 'FETCH_EVENTS',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'FetchEmits',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'FetchEventBase',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'FetchProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'FetchShopifyPartialProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FetchShopifyPartial/js-api',
    status: 'preview',
  },
  {
    name: 'FetchShopifySectionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FetchShopifySection/js-api',
    status: 'stable',
  },
  {
    name: 'FigureProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Figure/js-api',
    status: 'stable',
  },
  {
    name: 'FigureShopifyProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FigureShopify/js-api',
    status: 'stable',
  },
  {
    name: 'FigureTwicpicsProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FigureTwicpics/js-api',
    status: 'stable',
  },
  {
    name: 'FigureVideoProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FigureVideo/js-api',
    status: 'stable',
  },
  {
    name: 'FigureVideoTwicpicsProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FigureVideoTwicpics/js-api',
    status: 'stable',
  },
  {
    name: 'HEADER_NAMES',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Fetch/js-api',
    status: 'stable',
  },
  {
    name: 'HoverableBounds',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Hoverable/js-api',
    status: 'stable',
  },
  {
    name: 'HoverableProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Hoverable/js-api',
    status: 'stable',
  },
  {
    name: 'INDEXABLE_BOUNDARIES',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Indexable/js-api',
    status: 'stable',
  },
  {
    name: 'INDEXABLE_INSTRUCTIONS',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Indexable/js-api',
    status: 'stable',
  },
  {
    name: 'IndexableBoundary',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Indexable/js-api',
    status: 'stable',
  },
  {
    name: 'IndexableInstruction',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Indexable/js-api',
    status: 'stable',
  },
  {
    name: 'IndexableInterface',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withIndex/',
    status: 'stable',
  },
  {
    name: 'IndexableProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Indexable/js-api',
    status: 'stable',
  },
  {
    name: 'LargeTextProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/LargeText/js-api',
    status: 'stable',
  },
  {
    name: 'MenuBtnProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Menu/js-api',
    status: 'stable',
  },
  {
    name: 'MenuListProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Menu/js-api',
    status: 'stable',
  },
  {
    name: 'MenuProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Menu/js-api',
    status: 'stable',
  },
  {
    name: 'Modifier',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Action/js-api',
    status: 'stable',
  },
  {
    name: 'MODIFIERS',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Action/js-api',
    status: 'stable',
  },
  {
    name: 'ScrollRevealProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ScrollReveal/js-api',
    status: 'stable',
  },
  {
    name: 'ScrollToProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ScrollTo/js-api',
    status: 'stable',
  },
  {
    name: 'SECTIONS_PARAMETER',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/FetchShopifySection/index',
    status: 'stable',
  },
  {
    name: 'SentinelProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Sentinel/',
    status: 'stable',
  },
  {
    name: 'StickyProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Sticky/js-api',
    status: 'stable',
  },
  {
    name: 'TABS_ACTIVATIONS',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Tabs/js-api',
    status: 'stable',
  },
  {
    name: 'TabsActivation',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Tabs/js-api',
    status: 'stable',
  },
  {
    name: 'TabsEventPayload',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Tabs/js-api',
    status: 'stable',
  },
  {
    name: 'TabsProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Tabs/js-api',
    status: 'stable',
  },
  {
    name: 'TimerProgressProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Timer/js-api',
    status: 'stable',
  },
  {
    name: 'TimerProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Timer/js-api',
    status: 'stable',
  },
  {
    name: 'ToasterProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Toaster/js-api',
    status: 'stable',
  },
  {
    name: 'ToasterShowOptions',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Toaster/js-api',
    status: 'stable',
  },
  {
    name: 'ToastProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Toaster/js-api',
    status: 'stable',
  },
  {
    name: 'TRACK_PSEUDO_EVENTS',
    kind: 'constant',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Track/js-api',
    status: 'stable',
  },
  {
    name: 'TrackContextProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Track/js-api',
    status: 'stable',
  },
  {
    name: 'TrackProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Track/js-api',
    status: 'stable',
  },
  {
    name: 'TrackPseudoEvent',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Track/js-api',
    status: 'stable',
  },
  {
    name: 'TrackShopifyProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/Track/js-api',
    status: 'stable',
  },
  {
    name: 'Transitionable',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withTransition/',
    status: 'stable',
  },
  {
    name: 'TransitionInterface',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withTransition/',
    status: 'stable',
  },
  {
    name: 'TransitionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/withTransition/',
    status: 'stable',
  },
  {
    name: 'ViewTransitionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui',
    importPath: '@studiometa/ui',
    href: '/reference/items/ViewTransition/js-api',
    status: 'stable',
  },
  {
    name: 'AbstractMapboxControlProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'AbstractMapboxMapChildProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MAPBOX_CLUSTER_CONNECTED',
    kind: 'constant',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MAPBOX_MAP_CONNECTED',
    kind: 'constant',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxClusterItemProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxClusterProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxFullscreenControlProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxGeocoderProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxGeolocateControlProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxImageProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxImagesProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxLayerProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxMapProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxMarkerProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxNavigationControlProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxPopupProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'MapboxSourceProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/MapboxMap/js-api',
    status: 'stable',
  },
  {
    name: 'StoreLocatorProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-mapbox',
    importPath: '@studiometa/ui-mapbox',
    href: '/reference/items/StoreLocator/js-api',
    status: 'stable',
  },
  {
    name: 'MotionProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-motion',
    importPath: '@studiometa/ui-motion',
    href: '/reference/items/Motion/js-api',
    status: 'stable',
  },
  {
    name: 'MotionScrollTimelineProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-motion',
    importPath: '@studiometa/ui-motion',
    href: '/reference/items/MotionScrollTimeline/js-api',
    status: 'stable',
  },
  {
    name: 'MotionSequenceProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-motion',
    importPath: '@studiometa/ui-motion',
    href: '/reference/items/MotionSequence/js-api',
    status: 'stable',
  },
  {
    name: 'MotionViewProps',
    kind: 'type',
    package: 'npm:@studiometa/ui-motion',
    importPath: '@studiometa/ui-motion',
    href: '/reference/items/MotionView/js-api',
    status: 'stable',
  },
] satisfies ReferenceSymbol[];
