name: export-size

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/ui/**'
      - 'packages/ui-mapbox/**'
      - 'package-lock.json'

permissions:
  contents: read
  pull-requests: write

jobs:
  export_size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: weareikko/export-size@1
        with:
          packages: |
            @studiometa/ui:packages/ui
            @studiometa/ui-mapbox:packages/ui-mapbox
          build: npm run build:export-size
